name: Build/release

on: 
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run build
      - run: npm run package

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            "./dist/*.exe"
            "./dist/*.dmg"
            "./dist/*.deb"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
